intro/urls.py
from django.urls import path
from . import views

app_name = 'intro'
urlpatterns = [
    path('', views.profile, name='profile'),
]

posts/urls.py
from django.urls import path
from .views import main, new, create, show

app_name = 'posts'
urlpatterns = [
    path('new/',new, name="new"),
    path('create/',create, name="create"),
    path('', main, name="main"),
    path('show/<int:id>', show, name="show"),
]

resite/urls.py
from django.urls import path
from . import views

app_name = 'resite'
urlpatterns = [
    path('', views.resite, name="resite"),
]

svp1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('intro/', include('intro.urls')),
    path('resite/', include('resite.urls')),
    path('posts/', include('posts.urls')),
    path('', views.main, name="main"),
]

intro/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50, null=False)
    content = models.TextField()
    view_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

resite/models.py
from django.db import models

# Create your models here.

intro/views.py
from django.shortcuts import render

# Create your views here.


def profile(request):
    return render(request, 'intro/profile.html')

posts/views.py
from django.shortcuts import render, redirect
from .models import Post 

def new(request):
    return render(request, 'posts/new.html')


def create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        content = request.POST.get('content')
        Post.objects.create(title=title, content=content)
    return redirect('posts:main')

def main(request):
    posts = Post.objects.all()
    return render(request, 'posts/main.html', {'posts':posts})

def show(request, id):
    post = Post.objects.get(pk=id)
    return render(request, 'posts/show.html', {'post': post})

resite/views.py
from django.shortcuts import render

# Create your views here.


def resite(request):
    return render(request, 'resite/resite.html')

svp1/views.py
from django.shortcuts import render


def main(request):
    return render(request, 'main.html')

intro/templates/intro/profile.html
{% extends 'base.html' %}{% load static %} {% block content %}
<div>
  <h3>
    우리 사이트는 음향기기에 관심이 많으시고, 관심이 생기신 분들을 위한 음향기기
    관련 정보를 제공하고 있습니다.
  </h3>
</div>
<div>문의사항: 010-2024-2365</div>
{% endblock %}

posts/templates/posts/main.html
{% extends 'base.html' %} {% load static %} {% block content %} {% include
'shared/_navbar.html' %}
<div class="container">
  <h1>글 목록입니다.</h1>
  <a href="{% url 'posts:new' %}" class="btn btn-primary">새 글 작성</a>
  <div class="row">
    {% for post in posts %}
    <div class="col-md-4 col-12">
      <div class="card" style="width: 18rem; margin-top: 20px;">
        <div class="card-body">
          <h5 class="card-title">{{ post.title }}</h5>
          <p class="card-text">{{ post.content }}</p>
          <p>{{ post.created_at }}</p>
          <a href="{% url 'posts:show' post.pk %}" class="btn btn-primary"
            >상세보기</a
          >
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

posts/templates/posts/new.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h1>
    새로운 글 작성하기
  </h1>
  <form action="{% url 'posts:create' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label>글 제목</label>
      <input type="text" class="form-control" name="title" />
    </div>
    <div class="form-group">
      <label>글 내용</label>
      <textarea class="form-control" name="content"></textarea>
    </div>
    <input type="submit" value="글 작성" class="btn btn-outline-primary" />
  </form>
</div>
{% endblock %}

posts/templates/posts/show.html
{% extends 'base.html' %} {% block content %}
<h1>상세보기 페이지</h1>
<h3>글 제목 : {{ post.title }}</h3>
<br />
<h3>글 내용 : {{ post.content }}</h3>
<br />
<h3>작성 시각 : {{ post.created_at }}</h3>
<br />
<h3>조회수 : {{ post.view_count }}</h3>
<br />
<h3>수정 시각 : {{ post.updated_at }}</h3>
<br />
{% endblock %}

resite/templates/resite/resite.html
{% extends 'base.html' %} {% load static %} {% block content %}
<h1>
  <div
    class="btn-group"
    role="group"
    aria-label="Button group with nested dropdown"
  >
    <div class="btn-group" role="group">
      <button
        id="btnGroupDrop1"
        type="button"
        class="btn btn-secondary dropdown-toggle"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        네이버 카페
      </button>
      <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
        <a class="dropdown-item" href="https://cafe.naver.com/drhp"
          >닥터헤드폰</a
        >
        <a class="dropdown-item" href="https://cafe.naver.com/samaudio"
          >samaudio</a
        >
        <a class="dropdown-item" href="https://cafe.naver.com/fostex">1910C</a>
      </div>
    </div>

    <div class="btn-group" role="group">
      <button
        id="btnGroupDrop1"
        type="button"
        class="btn btn-secondary dropdown-toggle"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        청음샵
      </button>
      <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
        <a class="dropdown-item" href="http://www.schezade.co.kr/"
          >셰에라자드</a
        >
        <a class="dropdown-item" href="https://soundcat.com/">사운드캣</a>
        <a class="dropdown-item" href="http://www.fostexshop.co.kr/">1910샵</a>
      </div>
    </div>

    <div class="btn-group" role="group">
      <button
        id="btnGroupDrop1"
        type="button"
        class="btn btn-secondary dropdown-toggle"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        기타 사이트
      </button>
      <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
        <a
          class="dropdown-item"
          href="http://blog.naver.com/luric?proxyReferer=https%3A%2F%2Fsearch.naver.com%2Fsearch.naver%3Fsm%3Dtab_hty.top%26where%3Dnexearch%26query%3Dluric%26oquery%3D%25EB%25A3%25A8%25EB%25A6%25AD%26tqi%3DUwe4xdp0YiRssEfWRPhssssssQw-394284"
          >luric</a
        >
        <a class="dropdown-item" href="http://ko.goldenears.net/">사운드캣</a>
      </div>
    </div>
  </div>
</h1>

{% endblock %}

svp1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/project.css' %}" />

    <title>Golden ears</title>
  </head>
  <body>
    {% include 'shared/_navbar.html' %} {% block content %} {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
      integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

svp1/templates/main.html
{% extends 'base.html' %} {% load static %} {% block content %}
<h1>Recommendation For Golden Ears</h1>
<img src="{% static 'image/listener.jpg' %}" class="img" alt="listener" />
{% endblock %}

svp1/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'main' %}">Home</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'intro:profile' %}"
          >introduction <span class="sr-only">(current)</span></a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'resite:resite' %}">Site</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'posts:main' %}">글 목록</a>
      </li>
    </ul>
  </div>
</nav>